var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                   o        o     xxx           ",
   "                 o                           o     xx      xx    xx!xx          ",
   "    y     y      y     y                     xx       x  x       x!!!x          ",
   "                                     o                x!!x       xx!xx          ",
   "                                   xxxxx              x!!x        xvx       o   ",
   "                                                      xxxx                  xx  ",
   "  xx                    o                                                    x  ",
   "  x                    xxxx                 o                              o x  ",
   "  x                                       xxxx                          xxxxxx  ",
   "  x                                      xx                                  x  ",
   "  x  @                   o               xx                                o x  ",
   "  xxxxxxxxx        xxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxx ",
   "          x        x          x   x                  x     x                    ",
   "          x      xxx          x!!!x                  x!!!!!x                    ",
   "          xxxx!!!!!x          x!!!x                  x!!!!!x                    ",
   "           x!!!!!!!x          xxxxx                  xxxxxxx                    ",
   "           xxxxxxxxx                                                            ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                             xxxxxxxxxx  ",
   "                                      x!!x                     xxxx!!!!!xxxx                          !!!!!!!x!x  ",
   "                                                              xx!!!!!!!!!!!xx                                x!x  ",
   "                                                             xx             xx                               x!x  ",
   "                                       xxxxxxxxxx           x               !!                    y   y   y  x!x  ",
   "                                       !!!!!!!!!x!x         x     y   y                                     xx!x  ",
   "                                                x!x         x                                 xxxxxxxxxxxxxxx!!x  ",
   "                                                xvx         x     x   x                       y !!!!!!!!!!!!!!xx  ",
   "                 xxxxx                                       xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "               xxxyyyxxx                                    xx!!!!!!!!!!!xx                                       ",
   "              xxy     yxx                                      xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxvxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                         xx                    x     x                           !!x         x                    ",
   "                                               x     x                           !!xx        x                    ",
   "                 y y                        xxxxx    x                           !!x         x                    ",
   "                                     y         x!    x      y  y     x   x       !!x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x       !!xy        x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x   x!!!x  x    xx     !!!!!!    x   x   x y           xxx                    ",
   "     @       x      y  x        x   x   x!!!x  x    !x               x   x y x             !!x                    ",
   "    xxx      x     xxxxx        x   x   xxxxx  x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x                x       xx y xx         x     x               x     o     x x!!       x                    ",
   "!!!!x x!!!!!xxxxx      x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx     y    xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o     !!!!!       xx!!!!!!xx !                           xx                     ",
   "!!!!x x!!!!!!xy       xx!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!xxx       x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !          xxxx                                    ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !    y                                             ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !   xxx                                            "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                    !!  y  !!                                                                 ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   yyyy   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x             y      x!!!x                              ",
   "                                      x   x           x                     xxx         y y                   ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x y x           x           xyyyx                                       ",
   "                                      x   x    = = = =x     o                xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                          x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                  xvx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x!!!!!!!!!!!!!x   xxxxxxxxxxxxxxxxxxxxxxx                                    y   ",
   "   y                         xx           xx           x!!!!x                        xxx                      ",
   "  xxx                         x     y     x            x    x                       x!!!x                xxx  ",
   "  x x                         x    xxx    x            x y                          yxxxy                x x  ",
   "  x                           x    xxx    xxxxxxx      xxx               xxxxx                             x  ",
   "  x                           x           x                              x y x                             x  ",
   "  x               y           xx          x                              x   x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx  xx                             x  ",
   "  x                                o o    x                              x       x!!!!!!x                  x  ",
   "  x            xxxxxxx       xx           x                             xxx      x! yy !x        x         x  ",
   "  x            x!!!!!x        x    xxx    x                             x x      x! yy !x       xxx        x  ",
   "  x            x! y !x        xxxxxxxxxxxxx  x    x    x    x    x     xx xx     x!    !x       xxx        x  ",
   "  x      @          !x        x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                    y x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x y         ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                             y                    x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o            xxxxxxxxx             xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                       xx!!!!!xx                                                              ",
   "          o              xxx           xx  o  xx          xx                                                  ",
   "                                       xx ooo xx                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                o      o                      ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx      o                  o                 ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "       yy                                                        ||                                           ",
   "  xxxxxxxxxxx                                                                             o                   ",
   "  x!!!!!!!!!x o xxxxxxxxx o xxxxxxxxx o xx                                    o     o     x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                        yy                                           ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=       y          =      y         =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
